<header>
    <h1>Managing translations for 
        <select data-role="language" title="Change the current language" data-placement="right">
            <?php $languagesVerbose = $this->getPlaceholder(View_Admin::PH_TR_LANGUAGES); foreach($languagesVerbose as $languageCode => $languageText):?>
            <option value="<?php echo($languageCode);?>" <?php echo ($this->getPlaceholder(View_Admin::PH_TR_LANGUAGE) == $languageCode ? 'selected':'');?>>
                <?php echo($languageText);?>
            </option>
            <?php endforeach; ?>
        </select>
    </h1>
</header>
<?php if (is_array($this->getPlaceholder(View_Admin::PH_TR_ERRORS))):?>
<div class="row">
    <div class="alert alert-danger" role="alert">
        <p><span class="glyphicon glyphicon-warning-sign"></span> Please manually fix the following <b>Translation Cache</b> errors:</p>
        <ul>
            <?php foreach ($this->getPlaceholder(View_Admin::PH_TR_ERRORS) as $errLangCode => $errStrings):?>
            <li>
                <b><?php echo $languagesVerbose[$errLangCode];?></b>
                <ul>
                    <?php foreach ($errStrings as $errString):?>
                    <li><?php echo $errString;?></li>
                    <?php endforeach;?>
                </ul>
            </li>
            <?php endforeach;?>
        </ul>
    </div>
</div>
<?php endif;?>
<?php if (count($this->getPlaceholder(View_Admin::PH_TR_ENTRIES))):?>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th></th>
                <th>Singular</th>
                <th>Plural</th>
                <th>Translations</th>
            </tr>
        </thead>
        <tbody>
    <?php
    // For each entry
    foreach($this->getPlaceholder(View_Admin::PH_TR_ENTRIES) as /*@var $entry WordPress_Pot_Translations_Entry*/ $entry) : ?>
        <tr class="<?php echo (in_array(WordPress_Pot_Translations_Entry::FLAG_FUZZY, $entry->flags) ? 'info' : '');?>">
            <td><button type="button" data-role="remove" class="btn btn-default"><span class="glyphicon glyphicon-remove"></span></button></td>
            <td><?php echo htmlentities($entry->singular); ?></td>
            <td><?php echo $entry->isPlural ? htmlentities($entry->plural) : '<span class="glyphicon glyphicon-ban-circle"></span>';?></td>
            <td>
                <?php
                    // Prepare the number of translations
                    $numberOfPlurals = $entry->isPlural ? $this->getPlaceholder(View_Admin::PH_TR_NUMBER) : 1;

                    // Add list elements for all translations
                    for($i = 0; $i < $numberOfPlurals; $i++):
                        // Prepare the singular/plural/translation
                        $comments = (0 == $i) ? (1 == $numberOfPlurals ? 'Translation' : 'Singular') : 'Plural';

                        // Fuzzy flag
                        $comments .= in_array(WordPress_Pot_Translations_Entry::FLAG_FUZZY, $entry->flags) ? '; fuzzy' : '';

                        // Comments and context
                        $comments .= strlen($entry->extractedComments) || strlen($entry->context) ? '; ' . htmlentities(implode('; ', array_filter(array($entry->extractedComments, $entry->context)))) : '';
                ?>
                <textarea
                    rows="3"
                    spellcheck="false"
                    data-role="translation"
                    data-key="<?php echo htmlentities($entry->key()); ?>" 
                    data-index="<?php echo $i; ?>" 
                    placeholder="<?php echo $comments;?>"
                    title="<?php echo $comments;?>"
                    class="form-control"><?php echo (isset($entry->translations[$i]) ? htmlentities($entry->translations[$i]) : '');?></textarea>
                <?php 
                    endfor; 
                ?>
            </td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php else:?>
    <div class="row">
        <div class="alert alert-info" role="alert">
            <p>No internationalization strings found. Open a WordPress theme project and try again!</p>
        </div>
    </div>
<?php endif;?>