<div class="row">
    <h2>Edit current users</h2>
    <table class="table table-striped table-hover">
        <thead>
        <th>#</th>
        <th>E-mail</th>
        <th>Password</th>
        <th>Name</th>
        <th>Role</th>
        <th width="150" style="text-align: center;">Action</th>
        </thead>
        <tbody>
            <?php foreach ($this->getPlaceholder(View_Users::PH_USERS) as $user): ?>
                <tr>
                    <td><?php echo $user->id; ?></td>
                    <td><input type="email" name="email" class="form-control" value="<?php echo $user->email; ?>" placeholder="E-mail" disabled="disabled"/></td>
                    <td><input type="password" name="password" class="form-control" value="" placeholder="Leave empty for no change" disabled="disabled"/></td>
                    <td><input type="text" name="name" class="form-control" value="<?php echo $user->name; ?>" placeholder="Name" disabled="disabled"/></td>
                    <td>
                        <select name="role" class="form-control" disabled="disabled">
                            <?php foreach (Session::$roles as $role): ?>
                                <option<?php echo ($user->role == $role ? ' selected="selected"' : ''); ?>><?php echo $role; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                    <td style="text-align: center;">
                        <div class="btn-group">
                            <button type="button" title="Edit user" data-placement="top" data-toggle="tooltip" class="btn btn-default button-edit" data-id="<?php echo $user->id; ?>"><span class="glyphicon glyphicon-pencil"></span></button>
                            <button type="button" title="Re-initialize the WordPress environment" data-placement="top" data-toggle="tooltip" class="btn btn-default button-init" data-id="<?php echo $user->id; ?>"><span class="glyphicon glyphicon-flash"></span></button>
                            <button type="button" title="Delete user" data-placement="top" data-toggle="tooltip" class="btn btn-danger button-delete" data-id="<?php echo $user->id; ?>"><span class="glyphicon glyphicon-remove"></span></button>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<div class="row">
    <h2>Add a new user</h2>
    <form class="form-horizontal" autocomplete="off" id="newUserForm">
        <div class="form-group">
            <label for="newEmail" class="col-sm-2 control-label">E-mail</label>
            <div class="col-sm-10">
                <input type="email" required autofocus class="form-control" id="newEmail" placeholder="Email">
            </div>
        </div>
        <div class="form-group">
            <label for="newPassword" class="col-sm-2 control-label">Password</label>
            <div class="col-sm-10">
                <!--Prevent Firefox auto-complete-->
                <input type="text" style="display:none;" /><input type="password" style="display:none;" />
                <input type="password" required autofocus class="form-control" id="newPassword" placeholder="Password" value="">
            </div>
        </div>
        <div class="form-group">
            <label for="newName" class="col-sm-2 control-label">Name</label>
            <div class="col-sm-10">
                <input type="text" required autofocus class="form-control" id="newName" placeholder="Name">
            </div>
        </div>
        <div class="form-group">
            <label for="newRole" class="col-sm-2 control-label">Role</label>
            <div class="col-sm-10">
                <select id="newRole" class="form-control">
                    <?php foreach (Session::$roles as $role): ?>
                        <option><?php echo $role; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success button-add">Add User</button>
            </div>
        </div>
    </form>
</div>